### ISSUE TITLE
"IndexError: list index out of range" durinng "test" and "test single image" scipt

### ISSUE THREAD

**Issue by artem-bondarenko-ua** [wuhuikai/FastFCN#104]
/usr/bin/python3.8 /home/a.sysa/Videos/FastFCN/experiments/segmentation/test_single_image.py --dataset brain-tumor --model fcn --jpu JPU --backbone resnet50 --resume /home/a.sysa/Videos/FastFCN/experiments/segmentation/experiments/segmentation/runs/brain-tumor/fcn/brain-tumor-training/0.51.0model_best.pth.tar --input-path /home/a.sysa/Videos/FastFCN/encoding/datasets/BRAIN_TUMOR/images/train/y0.jpg --save-path /home/a.sysa/Videos/FastFCN/encoding/datasets/BRAIN_TUMOR/images/train/xxx0.jpg
Namespace(aux=False, aux_weight=0.2, backbone='resnet50', base_size=520, batch_size=16, checkname='default', crop_size=480, cuda=False, dataset='brain-tumor', dilated=False, epochs=120, ft=False, input_path='/home/a.sysa/Videos/FastFCN/encoding/datasets/BRAIN_TUMOR/images/train/y0.jpg', jpu='JPU', lateral=False, lr=0.01, lr_scheduler='poly', mode='testval', model='fcn', model_zoo=None, momentum=0.9, ms=False, no_cuda=False, no_val=False, resume='/home/a.sysa/Videos/FastFCN/experiments/segmentation/experiments/segmentation/runs/brain-tumor/fcn/brain-tumor-training/0.51.0model_best.pth.tar', save_folder='experiments/segmentation/results2', save_path='/home/a.sysa/Videos/FastFCN/encoding/datasets/BRAIN_TUMOR/images/train/xxx0.jpg', se_loss=False, se_weight=0.2, seed=1, split='val', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
=> loaded checkpoint '/home/a.sysa/Videos/FastFCN/experiments/segmentation/experiments/segmentation/runs/brain-tumor/fcn/brain-tumor-training/0.51.0model_best.pth.tar' (epoch 1)

MultiEvalModule: base_size 520, crop_size 480
Traceback (most recent call last):
  File "/home/a.sysa/Videos/FastFCN/experiments/segmentation/test_single_image.py", line 70, in <module>
    test(args)
  File "/home/a.sysa/Videos/FastFCN/experiments/segmentation/test_single_image.py", line 56, in test
    output = evaluator.parallel_forward(img)[0]
  File "/home/a.sysa/Videos/FastFCN/encoding/models/base.py", line 110, in parallel_forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 80, in parallel_apply
    _worker(0, modules[0], inputs[0], kwargs_tup[0], devices[0])
_IndexError: list index out of range_

**Comment by wuhuikai** [comment]
I believe that multiple GPUs should be used.

**Comment by artem-bondarenko-ua** [comment]
What if i have only integrated gpu?

**Comment by wuhuikai** [comment]
use `latest` branch or modify the code accordingly.
