### ISSUE TITLE
FastFCN has been supported by MMSegmentation.

### ISSUE THREAD

**Issue by MengzhangLI** [wuhuikai/FastFCN#106]
Hi, right now FastFCN has been supported by [MMSegmentation](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/fastfcn). We do find using JPU with smaller feature maps from backbone could get similar or higher performance than original models with larger feature maps.

There is still something to do for us, for example, we do not find obviously improvement about FPS in our implementation, thus we would try to figure it out in the future.

Anyway, thanks for your work and hope more people from community could use FastFCN.

Best,

**Comment by wuhuikai** [comment]
Thanks for your implementation in MMSegmentaion. Could you please share your result about FPS? Which backbones  did you experiment with?

**Comment by MengzhangLI** [comment]
More details could be found [here](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/fastfcn).

Backbone is ResNet50, decoder head is PSPNet, EncNet and DeepLabV3.

**Comment by wuhuikai** [comment]
As shown in the paper, the advantage is more significant when using ResNet101 as the backbone.

**Comment by edwardyehuang** [comment]
Why not submit to a conference? Although it is a 2019 paper, i think it is still worth a CVPR. Based on huge number of expierment I did, JPU can get simliar or better performance than dilation mode, even on Swin-Large or ConvNextXt-Large.

**Comment by MengzhangLI** [comment]
Could you list your numerical results about JPU + Swin/ConvNeXt? It would be better if your experiments were based on MMSegmentation codebase.

**Comment by MengzhangLI** [comment]
> Why not submit to a conference? Although it is a 2019 paper, i think it is still worth a CVPR. Based on huge number of expierment I did, JPU can get simliar or better performance than dilation mode, even on Swin-Large or ConvNextXt-Large.

Could you list your numerical results about JPU + Swin/ConvNeXt? It would be better if your experiments were based on MMSegmentation codebase.

**Comment by edwardyehuang** [comment]
> > Why not submit to a conference? Although it is a 2019 paper, i think it is still worth a CVPR. Based on huge number of expierment I did, JPU can get simliar or better performance than dilation mode, even on Swin-Large or ConvNextXt-Large.
> 
> Could you list your numerical results about JPU + Swin/ConvNeXt? It would be better if your experiments were based on MMSegmentation codebase.

Sorry, I am not using mmseg atm. I will provide some results in near future.

**Comment by wuhuikai** [comment]
> Why not submit to a conference? Although it is a 2019 paper, i think it is still worth a CVPR. Based on huge number of expierment I did, JPU can get simliar or better performance than dilation mode, even on Swin-Large or ConvNextXt-Large.

If you're interested, we can work on it together : )

**Comment by MengzhangLI** [comment]
> > > Why not submit to a conference? Although it is a 2019 paper, i think it is still worth a CVPR. Based on huge number of expierment I did, JPU can get simliar or better performance than dilation mode, even on Swin-Large or ConvNextXt-Large.
> > 
> > 
> > Could you list your numerical results about JPU + Swin/ConvNeXt? It would be better if your experiments were based on MMSegmentation codebase.
> 
> Sorry, I am not using mmseg atm. I will provide some results in near future.

OK, got it. Swin and ConvNeXt official repos were both implemented based on MMSegmentation.

**Comment by MengzhangLI** [comment]
https://paperswithcode.com/paper/car-class-aware-regularizations-for-semantic-1 @wuhuikai
