### ISSUE TITLE
In order to run this on a different dataset say CamVid what changes need to be made

### ISSUE THREAD

**Issue by sparshgarg23** [wuhuikai/FastFCN#107]
I was thinking of evaluating the model's performance by training it on camvid ,as such apart from writing the camvid dataset file ,what other changes need to be made ?

**Comment by wuhuikai** [comment]
some hyper-params in https://github.com/wuhuikai/FastFCN/blob/master/experiments/segmentation/option.py.

**Comment by sparshgarg23** [comment]
ok thanks
