### ISSUE TITLE
Code implemention

### ISSUE THREAD

**Issue by BlossomingL** [wuhuikai/FastFCN#11]
I would like to ask which file code implements the convolution network in the paper graph

**Comment by wuhuikai** [comment]
See [here](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/encoding/models/base.py#L52) and [here](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/encoding/nn/customize.py#L153).
