### ISSUE TITLE
Why use seperable convolutions with dilation factor?

### ISSUE THREAD

**Issue by sparshgarg23** [wuhuikai/FastFCN#110]
In the paper under the JPU section it is mentioned that
```
after processing the feature map with regular convolution,they are upsampled and then concatenated
this concatenated feature map is then subjected to seperable convolutions with different dilation factors to capture  the relation between y0m and the rest of ym.
```
So my question is that since dilated convolution also uses  convolution filters with different dilation factors,how  is fast fcn different.Is it the use of depth wise seperable convolutions that makes it more efficient.Also wouldn't adding the dilation factor add to the overhead?

**Comment by wuhuikai** [comment]
1. Efficient: FastFCN employs 32s backbones, while others using 8s backbones.
2. FLOPS(conv) = FLOPS(dilated conv)
