### ISSUE TITLE
Run Time error when trying to train AdeK20 dataset

### ISSUE THREAD

**Issue by chandratejatiriveedhi** [wuhuikai/FastFCN#111]
Hi, thank you very much for your work. 
I try to run your code to train a model on the adek20 dataset on encnet with resnet50 backbone.But I got the following error:
RuntimeError: Failed downloading url https://hangzh.s3.amazonaws.com/encoding/models/resnet50-ebb6acbb.zip
I find the problem is I can not download the pretrained model.

Do you know what is the command to run this training on linux machine and do you know the location of the pretrained model?

So, How can I solve this problem.
Thanks for your consideration.

**Comment by wuhuikai** [comment]
Please refer to [here](https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/models/model_store.py).
