### ISSUE TITLE
how to Change SynBN to regular BN ?

### ISSUE THREAD

**Issue by 10183308** [wuhuikai/FastFCN#12]
how to Change SynBN to regular BN ?
could you help me?

thakn you very much.

**Comment by alphaccw** [comment]
model = get_segmentation_model() 
define norm_layer to be torch.nn.BatchNorm2d solve my problem.

**Comment by 10183308** [comment]
@alphaccw i have change the norm_layer ,but it also occur the problem. like below:
AttributeError: 'NoneType' object has no attribute 'run_slave'
![1](https://user-images.githubusercontent.com/23359860/56104098-df5a8600-5f68-11e9-9a79-19c3582b999e.png)
Could you help me ?
thank you very much

**Comment by alphaccw** [comment]
@10183308 
by this changing, i can successfully run psp and deeplab models, enc seems still have some problem, i didnot go into it yet. 
BTW, i remember i need to set as  'norm_layer=torch.nn.BatchNorm2d', the full name...i canot accesss to the machine now, so i cant check at the moment

**Comment by wuhuikai** [comment]
1. Modify this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/train.py#L54) to `se_loss = args.se_loss, norm_layer = torch.nn.BatchNorm2d,`
2. Modify this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/train.py#L111) to `loss = self.criterion(*outputs, target)`
3. Remove this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/train.py#L132)
4. Modify this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/encoding/models/encnet.py#L53) to `nn.BatchNorm1d(ncodes),`
5. Reinstall FastFCN
```
pip uninstall fast_fcn
PATH=.:$PATH
python setup.py install
```

![Screenshot from 2019-04-16 16-07-01](https://user-images.githubusercontent.com/6862805/56192779-b7028280-6061-11e9-816b-de0d3ccec9b3.png)

**Comment by abhimanyuchadha96** [comment]
Still doesn't work

**Comment by wuhuikai** [comment]
Please give the error message in detail.

**Comment by SangerY** [comment]
first, I have this problem, https://github.com/wuhuikai/FastFCN/issues/10 when train
I modified four places you mentioned, and then run in docker，use single gpu
```
CUDA_VISIBLE_DEVICES=0 python train.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --checkname encnet_res50_pcontext \
    --batch-size 1
```
get 
![1565141350(1)](https://user-images.githubusercontent.com/12136347/62588157-4bd20a00-b8f7-11e9-8bad-230a2a952e8f.png)
then I add --workers 1
still error
![1565141849(1)](https://user-images.githubusercontent.com/12136347/62588486-6e185780-b8f8-11e9-9788-1a08c28849da.png)

**Comment by wuhuikai** [comment]
~~5. Remove `DataParallelModel` from this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/train.py#L75).
6. Remove `DataParallelCriterion ` from this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/train.py#L76).
7. Undo `2`: Modify this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/train.py#L111) to `loss = self.criterion(outputs, target)`~~

**Comment by SangerY** [comment]
still the same error.
my environment，python3.7, pytorch1.0.1, cuda 9.0, cudnn 7.4.2, GTX1080，using docker 
is there anything wrong with my environment?
I can run test, test_fps and predict scripts successfully.

**Comment by wuhuikai** [comment]
Have you reinstalled the package after modifying the code?

**Comment by SangerY** [comment]
No. which package need to be reinstalled?

**Comment by wuhuikai** [comment]
```
pip uninstall fast_fcn
PATH=.:$PATH
python setup.py install
```
If you want to modify the code without reinstalling every time, then
```
pip uninstall fast_fcn
PATH=.:$PATH
python setup.py develop
```

Besides, I think step 5-7 is unnecessary, which can be skipped.

**Comment by SangerY** [comment]
Step 5-7 is unnecessary.
Thank you very much.
