### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by loveis98** [wuhuikai/FastFCN#19]
Hello! Will 12 GB of single GPU be enough to train your model on a small dataset? And may be you can publish your pretrained model (dataset no matter)? It would be great)

**Comment by wuhuikai** [comment]
1. The pre-trained model can be found [here](https://github.com/wuhuikai/FastFCN#pcontext).
2. A single GPU is enough if you freeze all the BN layers.

**Comment by meanmee** [comment]
@wuhuikai could you show us how to make a custom dataset to fit into the training process? what is the data structure?

**Comment by wuhuikai** [comment]
Please refer to the [`Base`](https://github.com/wuhuikai/FastFCN/blob/master/encoding/datasets/base.py) class and a [`concrete`](https://github.com/wuhuikai/FastFCN/blob/master/encoding/datasets/pcontext.py) class.
