### ISSUE TITLE
关于

### ISSUE THREAD

**Issue by BlossomingL** [wuhuikai/FastFCN#22]
您好，为什么我把JPU替换掉我自己的网络中的dilated conv层，速度和时间并没有提升？

**Comment by wuhuikai** [comment]
需要同时增加`pooling/stride conv`

**Comment by BlossomingL** [comment]
不好意思，我不是太明白。。。

**Comment by BlossomingL** [comment]
因为我的原本网络的dilated conv层前后分别有stride conv和deconv层，您的意思是将哪里的去除。

**Comment by wuhuikai** [comment]
在分割中，最后两个阶段的操作是去除降采样同时加大dilation，这样可以保证最后得到的feature map是输入图像的1/8。在我们的方法中，最后两个阶段的dilation是1，降采样操作也没有去除，最后得到的feature map是输入图像的1/32，然后经过我们的JPU变为输入图像的1/8.

**Comment by wuhuikai** [comment]
在本身就有stride conv的情况下，是不需要使用我们的方法的

**Comment by 2qwerty** [comment]
我们的网络，前面使用了类似论文中提出的5层(conv)encoder结构，使用您提出的JPU 替换膨胀卷积层 连接encoder部分，但是速度并没有提升?

**Comment by BlossomingL** [comment]
不好意思，我还有个问题就是代码里面SeparableConv2d(3*width, width, kernel_size=3, padding=1, dilation=1, bias=False)，这里经过了一次dilated conv,论文里面用了四次，那速度不跟原始的有dilated conv的一样（甚至速度会有下降）？

**Comment by wuhuikai** [comment]
@2qwerty Backbone是用的哪一个网络？Backbone的output stride是多少？

**Comment by wuhuikai** [comment]
@LinXXXX JPU能加速的原理是Backbone的output stride从8升到32。其主要作用是把1/32的feature map重新变回1/8，同时取得相近或更好的性能。

**Comment by BlossomingL** [comment]
代码中的feat1 = F.upsample(self.conv1(self.pool1(x)), (h, w), **self._up_kwargs)，F.upsample在tensorflow中能用简单的tf.image.resize_images()达到一样效果吗？感谢回答！

**Comment by wuhuikai** [comment]
`F.upsample`用于双线性插值上采样，等价于`tf.image.resize_images`.

**Comment by lifeiwen** [comment]
请问你是怎么开始训练的？用的什么指令
