### ISSUE TITLE
请问必须通过代码下载数据集才能训练吗？我自己先下载好不行吗？AssertionError: Please setup the dataset usingencoding/scripts/prepare_ade20k.py

### ISSUE THREAD

**Issue by lifeiwen** [wuhuikai/FastFCN#23]

**Comment by lifeiwen** [comment]
出现这个错误直接在路径下python train.py

**Comment by wuhuikai** [comment]
Please put your dataset in `~/.encoding/data/ADEChallengeData2016`

**Comment by lifeiwen** [comment]
@wuhuikai 你好，我把数据放在你说的路径还是AssertionError: Please setup the dataset usingencoding/scripts/prepare_ade20k.py这个问题

**Comment by wuhuikai** [comment]
What's your OS, Windows or Linux?

**Comment by lifeiwen** [comment]
@wuhuikai linux 把数据路径改成了绝对路径也还是有这个问题

**Comment by wuhuikai** [comment]
Can you show the structure of `~/.encoding/data`?

**Comment by lifeiwen** [comment]
@wuhuikai Hi我的数据是FastFCN/encoding/data/ADEChallengeData2016/

**Comment by lifeiwen** [comment]
(torch1.0) lf@110:~/Semantic segmentation/FastFCN/experiments/segmentation$ python train.py 
Namespace(aux=False, aux_weight=0.2, backbone='resnet50', base_size=520, batch_size=16, checkname='default', crop_size=480, cuda=True, dataset='ade20k', dilated=False, epochs=120, ft=False, jpu=False, lateral=False, lr=0.01, lr_scheduler='poly', mode='testval', model='encnet', model_zoo=None, momentum=0.9, ms=False, no_cuda=False, no_val=False, resume=None, save_folder='results', se_loss=False, se_weight=0.2, seed=1, split='val', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
BaseDataset: base_size 520, crop_size 480
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    trainer = Trainer(args)
  File "train.py", line 39, in __init__
    **data_kwargs)
  File "/home/lf/anaconda3/envs/torch1.0/lib/python3.5/site-packages/encoding/datasets/__init__.py", line 19, in get_segmentation_dataset
    return datasets[name.lower()](**kwargs)
  File "/home/lf/anaconda3/envs/torch1.0/lib/python3.5/site-packages/encoding/datasets/ade20k.py", line 25, in __init__
    "encoding/scripts/prepare_ade20k.py"
AssertionError: Please setup the dataset usingencoding/scripts/prepare_ade20k.py

**Comment by wuhuikai** [comment]
I see. Please put your dataset in `/home/[USER NAME]/.encoding/data/ADEChallengeData2016`
