### ISSUE TITLE
包调用的问题

### ISSUE THREAD

**Issue by Chao86** [wuhuikai/FastFCN#24]
运行train.py中import encoding.utils as utils会出现ModuleNotFoundError: No module named 'encoding'的错误提示，改为 import FastFCN-master.encoding.utils as utils时出现”  File "D:\Deep learning\FastFCN\encoding\__init__.py", line 12, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'FastFCN.encoding.version'“的错误，请问__init__.py中的version指的是什么，如何解决？

**Comment by wuhuikai** [comment]
Have you run `python setup.py install`?

**Comment by XiaoAHeng** [comment]
> Have you run python setup.py insta

**Comment by Chao86** [comment]
> Have you run python setup.py install?

Yes, but I am a tyro, somdthing wrong is difficult to handle for me .Sorry to bother you

**Comment by wuhuikai** [comment]
@Chao86 The code in branch `latest` is now ready, which uses official `SyncBatchNorm` and can run on all OS with `PyTorch>=1.1.0`.
