### ISSUE TITLE
I have a question!

### ISSUE THREAD

**Issue by lifeiwen** [wuhuikai/FastFCN#26]

**Comment by lifeiwen** [comment]
When I run
#train
CUDA_VISIBLE_DEVICES=0 python train.py --dataset ade20k             --model encnet --jpu --aux --se-loss             --backbone resnet50 --checkname encnet_res50_ade20k_train
i have changed SynBN to regular BN  and changed the batch size to 4 ,but i still have this error:
AttributeError: 'NoneType' object has no attribute 'run_slave', How to solve it?thank you for your help!

**Comment by wuhuikai** [comment]
Please show the diff between your src and this repo.

**Comment by wuhuikai** [comment]
@lifeiwen The code in branch `latest` is now ready, which uses official `SyncBatchNorm` and can run on all OS with `PyTorch>=1.1.0`.
