### ISSUE TITLE
Inferencing on real world images

### ISSUE THREAD

**Issue by mrayush18** [wuhuikai/FastFCN#27]
Can you guide me on how to do inferencing on outside images. you have used pytorch encoding repo for data loading and preprocessing, so can you specify how can I use it to make inferencing.

**Comment by wuhuikai** [comment]
1. Write your own dataset as [this](https://github.com/wuhuikai/FastFCN/blob/master/encoding/datasets/pcontext.py) file.
2. Modify [this](https://github.com/wuhuikai/FastFCN/blob/master/encoding/datasets/__init__.py) file to add your own dataset.
3. `python test.py --dataset [your_data_set]`.
