### ISSUE TITLE
prepare_cityscapes.py not working

### ISSUE THREAD

**Issue by mhamedLmarbouh** [wuhuikai/FastFCN#28]
the download URLs aren't correct 
`_CITY_DOWNLOAD_URLS = [
        ('gtFine_trainvaltest.zip', '99f532cb1af174f5fcc4c5bc8feea8c66246ddbc'),
        ('leftImg8bit_trainvaltest.zip', '2c0b77ce9933cc635adda307fbba5566f5d9d404')]
`
and the download function is never called

**Comment by wuhuikai** [comment]
We didn't take an experiment on Cityscapes, please ask the question in this [repo](https://github.com/zhanghang1989/PyTorch-Encoding).
