### ISSUE TITLE
A problem in `test_fps_params.py`.

### ISSUE THREAD

**Issue by Tramac** [wuhuikai/FastFCN#29]
Hi, thank you for your meaningful work! 
I have a doubt about [`test_fps_params.py`](https://github.com/wuhuikai/FastFCN/blob/master/experiments/segmentation/test_fps_params.py). Why does it perform two loop operations ([loop1](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/test_fps_params.py#L27), [loop2](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/test_fps_params.py#L31))?What is the role of loop1?

**Comment by wuhuikai** [comment]
The first loop warms up the GPU.
