### ISSUE TITLE
请问是否可以开源具体的网络结构

### ISSUE THREAD

**Issue by luanyi93** [wuhuikai/FastFCN#30]
我对 JPU 很感兴趣，也正在尝试复现。在论文中，我没有找到具体的 JPU 网络层数（通道数），代码中也没有找到 JPU 的实现细节。请问是否可以分享一下具体的网络结构，这样也方便大家引用 JPU 这个方法。

**Comment by wuhuikai** [comment]
JPU is [here](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/encoding/nn/customize.py#L153).

**Comment by luanyi93** [comment]
看到了，谢谢！
