### ISSUE TITLE
Pretrained models error on untarring. 

### ISSUE THREAD

**Issue by neevparikh** [wuhuikai/FastFCN#32]
All the models that relate to the ade20k dataset give me errors when I try to untar the downloaded model. Is there anything I can do?

**Comment by wuhuikai** [comment]
It's not a `tar` but a `PyTorch` model. Load it as [here](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/test.py#L55).

**Comment by neevparikh** [comment]
Ah okay, should I rename it or not?

**Comment by wuhuikai** [comment]
Nop, just as it is.
