### ISSUE TITLE
Test a single image

### ISSUE THREAD

**Issue by Onimee58** [wuhuikai/FastFCN#36]
After the training is complete , with the trained model ,how do i segment a single image in any specific folder  ?

**Comment by wuhuikai** [comment]
We do not support testing a single image. Please write your own script.
Try to implement a new dataset in this [folder](https://github.com/wuhuikai/FastFCN/blob/master/encoding/datasets/) and run [`test.py`](https://github.com/wuhuikai/FastFCN/blob/master/experiments/segmentation/test.py) with your own dataset.

**Comment by Onimee58** [comment]
Ok , thanks a lot
