### ISSUE TITLE
自带的test文件是计算的59类的Miou还是60类的?

### ISSUE THREAD

**Issue by Anikily** [wuhuikai/FastFCN#39]

**Comment by Anikily** [comment]
如果是59类的话我怎么计算60类的呢？

**Comment by Anikily** [comment]
而且Pascal context dataset类里面写的num_classes=59,但是mapping有60个是什么意思呢？

**Comment by wuhuikai** [comment]
59; for 60 classes, please see [here](https://github.com/zhanghang1989/PyTorch-Encoding/issues/127#issuecomment-451353034).
Pascal context contains 60 classes, but when training, we only use 59 classes (no background).
