### ISSUE TITLE
problem in testing

### ISSUE THREAD

**Issue by Onimee58** [wuhuikai/FastFCN#40]
used this for testing
 CUDA_VISIBLE_DEVICES=4,5,6,7 python test.py --dataset ade20k --model encnet --jpu --aux --se-loss --backbone resnet101 --resume 'runs/ade20k/encnet/encnet_res50_ade20k_train/model_best.pth.tar' --split test --mode test

showed this error : 
Namespace(aux=True, aux_weight=0.2, backbone='resnet101', base_size=520, batch_size=16, checkname='default', crop_size=480, cuda=True, dataset='ade20k', dilated=False, epochs=120, ft=False, jpu=True, lateral=False, lr=0.01, lr_scheduler='poly', mode='test', model='encnet', model_zoo=None, momentum=0.9, ms=False, no_cuda=False, no_val=False, resume='runs/ade20k/encnet/encnet_res50_ade20k_train/model_best.pth.tar', save_folder='results', se_loss=True, se_weight=0.2, seed=1, split='test', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)                                                      Traceback (most recent call last):                                                                                                                                                                                   File "test.py", line 91, in <module>                                                                                                                                                                                 test(args)                                                                                                                                                                                                       File "test.py", line 57, in test                                                                                                                                                                                     model.load_state_dict(checkpoint['state_dict'])                                                                                                                                                                  File "/home/akmmrahman/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict                                                                                               self.__class__.__name__, "\n\t".join(error_msgs)))                                                                                                                                                             RuntimeError: Error(s) in loading state_dict for EncNet:                                                                                                                                                                   Missing key(s) in state_dict: "pretrained.layer3.6.conv1.weight", "pretrained.layer3.6.bn1.weight", "pretrained.layer3.6.bn1.bias", "pretrained.layer3.6.bn1.running_mean", "pretrained.layer3.6.bn1.running_var", "pretrained.layer3.6.conv2.weight", "pretrained.layer3.6.bn2.weight", "pretrained.layer3.6.bn2.bias", "pretrained.layer3.6.bn2.running_mean", "pretrained.layer3.6.bn2.running_var", "pretrained.layer3.6.conv3.weight", "pretrained.layer3.6.bn3.weight", "pretrained.layer3.6.bn3.bias", "pretrained.layer3.6.bn3.running_mean", "pretrained.layer3.6.bn3.running_var", "pretrained.layer3.7.conv1.weight", "pretrained.layer3.7.bn1.weight", "pretrained.layer3.7.bn1.bias", "pretrained.layer3.7.bn1.running_mean", "pretrained.layer3.7.bn1.running_var", "pretrained.layer3.7.conv2.weight", "pretrained.layer3.7.bn2.weight", "pretrained.layer3.7.bn2.bias", "pretrained.layer3.7.bn2.running_mean", "pretrained.layer3.7.bn2.running_var", "pretrained.layer3.7.conv3.weight", "pretrained.layer3.7.bn3.weight", "pretrained.layer3.7.bn3.bias", "pretrained.layer3.7.bn3.running_mean", "pretrained.layer3.7.bn3.running_var", "pretrained.layer3.8.conv1.weight", "pretrained.layer3.8.bn1.weight", "pretrained.layer3.8.bn1.bias", "pretrained.layer3.8.bn1.running_mean", "pretrained.layer3.8.bn1.running_var", "pretrained.layer3.8.conv2.weight", "pretrained.layer3.8.bn2.weight", "pretrained.layer3.8.bn2.bias", "pretrained.layer3.8.bn2.running_mean", "pretrained.layer3.8.bn2.running_var", "pretrained.layer3.8.conv3.weight", "pretrained.layer3.8.bn3.weight", "pretrained.layer3.8.bn3.bias", "pretrained.layer3.8.bn3.running_mean", "pretrained.layer3.8.bn3.running_var", "pretrained.layer3.9.conv1.weight", "pretrained.layer3.9.bn1.weight", "pretrained.layer3.9.bn1.bias", "pretrained.layer3.9.bn1.running_mean", "pretrained.layer3.9.bn1.running_var", "pretrained.layer3.9.conv2.weight", "pretrained.layer3.9.bn2.weight", "pretrained.layer3.9.bn2.bias", "pretrained.layer3.9.bn2.running_mean", "pretrained.layer3.9.bn2.running_var", "pretrained.layer3.9.conv3.weight", "pretrained.layer3.9.bn3.weight", "pretrained.layer3.9.bn3.bias", "pretrained.layer3.9.bn3.running_mean", "pretrained.layer3.9.bn3.running_var", "pretrained.layer3.10.conv1.weight", "pretrained.layer3.10.bn1.weight", "pretrained.layer3.10.bn1.bias", "pretrained.layer3.10.bn1.running_mean", "pretrained.layer3.10.bn1.running_var", "pretrained.layer3.10.conv2.weight", "pretrained.layer3.10.bn2.weight", "pretrained.layer3.10.bn2.bias", "pretrained.layer3.10.bn2.running_mean", "pretrained.layer3.10.bn2.running_var", "pretrained.layer3.10.conv3.weight", "pretrained.layer3.10.bn3.weight", "pretrained.layer3.10.bn3.bias", "pretrained.layer3.10.bn3.running_mean", "pretrained.layer3.10.bn3.running_var", "pretrained.layer3.11.conv1.weight", "pretrained.layer3.11.bn1.weight", "pretrained.layer3.11.bn1.bias", "pretrained.layer3.11.bn1.running_mean", "pretrained.layer3.11.bn1.running_var", "pretrained.layer3.11.conv2.weight", "pretrained.layer3.11.bn2.weight", "pretrained.layer3.11.bn2.bias", "pretrained.layer3.11.bn2.running_mean", "pretrained.layer3.11.bn2.running_var", "pretrained.layer3.11.conv3.weight", "pretrained.layer3.11.bn3.weight", "pretrained.layer3.11.bn3.bias", "pretrained.layer3.11.bn3.running_mean", "pretrained.layer3.11.bn3.running_var", "pretrained.layer3.12.conv1.weight", "pretrained.layer3.12.bn1.weight", "pretrained.layer3.12.bn1.bias", "pretrained.layer3.12.bn1.running_mean", "pretrained.layer3.12.bn1.running_var", "pretrained.layer3.12.conv2.weight", "pretrained.layer3.12.bn2.weight", "pretrained.layer3.12.bn2.bias", "pretrained.layer3.12.bn2.running_mean", "pretrained.layer3.12.bn2.running_var", "pretrained.layer3.12.conv3.weight", "pretrained.layer3.12.bn3.weight", "pretrained.layer3.12.bn3.bias", "pretrained.layer3.12.bn3.running_mean", "pretrained.layer3.12.bn3.running_var", "pretrained.layer3.13.conv1.weight", "pretrained.layer3.13.bn1.weight", "pretrained.layer3.13.bn1.bias", "pretrained.layer3.13.bn1.running_mean", "pretrained.layer3.13.bn1.running_var", "pretrained.layer3.13.conv2.weight", "pretrained.layer3.13.bn2.weight", "pretrained.layer3.13.bn2.bias", "pretrained.layer3.13.bn2.running_mean", "pretrained.layer3.13.bn2.running_var", "pretrained.layer3.13.conv3.weight", "pretrained.layer3.13.bn3.weight", "pretrained.layer3.13.bn3.bias", "pretrained.layer3.13.bn3.running_mean", "pretrained.layer3.13.bn3.running_var", "pretrained.layer3.14.conv1.weight", "pretrained.layer3.14.bn1.weight", "pretrained.layer3.14.bn1.bias", "pretrained.layer3.14.bn1.running_mean", "pretrained.layer3.14.bn1.running_var", "pretrained.layer3.14.conv2.weight", "pretrained.layer3.14.bn2.weight", "pretrained.layer3.14.bn2.bias", "pretrained.layer3.14.bn2.running_mean", "pretrained.layer3.14.bn2.running_var", "pretrained.layer3.14.conv3.weight", "pretrained.layer3.14.bn3.weight", "pretrained.layer3.14.bn3.bias", "pretrained.layer3.14.bn3.running_mean", "pretrained.layer3.14.bn3.running_var", "pretrained.layer3.15.conv1.weight", "pretrained.layer3.15.bn1.weight", "pretrained.layer3.15.bn1.bias", "pretrained.layer3.15.bn1.running_mean", "pretrained.layer3.15.bn1.running_var", "pretrained.layer3.15.conv2.weight", "pretrained.layer3.15.bn2.weight", "pretrained.layer3.15.bn2.bias", "pretrained.layer3.15.bn2.running_mean", "pretrained.layer3.15.bn2.running_var", "pretrained.layer3.15.conv3.weight", "pretrained.layer3.15.bn3.weight", "pretrained.layer3.15.bn3.bias", "pretrained.layer3.15.bn3.running_mean", "pretrained.layer3.15.bn3.running_var", "pretrained.layer3.16.conv1.weight", "pretrained.layer3.16.bn1.weight", "pretrained.layer3.16.bn1.bias", "pretrained.layer3.16.bn1.running_mean", "pretrained.layer3.16.bn1.running_var", "pretrained.layer3.16.conv2.weight", "pretrained.layer3.16.bn2.weight", "pretrained.layer3.16.bn2.bias", "pretrained.layer3.16.bn2.running_mean", "pretrained.layer3.16.bn2.running_var", "pretrained.layer3.16.conv3.weight", "pretrained.layer3.16.bn3.weight", "pretrained.layer3.16.bn3.bias", "pretrained.layer3.16.bn3.running_mean", "pretrained.layer3.16.bn3.running_var", "pretrained.layer3.17.conv1.weight", "pretrained.layer3.17.bn1.weight", "pretrained.layer3.17.bn1.bias", "pretrained.layer3.17.bn1.running_mean", "pretrained.layer3.17.bn1.running_var", "pretrained.layer3.17.conv2.weight", "pretrained.layer3.17.bn2.weight", "pretrained.layer3.17.bn2.bias", "pretrained.layer3.17.bn2.running_mean", "pretrained.layer3.17.bn2.running_var", "pretrained.layer3.17.conv3.weight", "pretrained.layer3.17.bn3.weight", "pretrained.layer3.17.bn3.bias", "pretrained.layer3.17.bn3.running_mean", "pretrained.layer3.17.bn3.running_var", "pretrained.layer3.18.conv1.weight", "pretrained.layer3.18.bn1.weight", "pretrained.layer3.18.bn1.bias", "pretrained.layer3.18.bn1.running_mean", "pretrained.layer3.18.bn1.running_var", "pretrained.layer3.18.conv2.weight", "pretrained.layer3.18.bn2.weight", "pretrained.layer3.18.bn2.bias", "pretrained.layer3.18.bn2.running_mean", "pretrained.layer3.18.bn2.running_var", "pretrained.layer3.18.conv3.weight", "pretrained.layer3.18.bn3.weight", "pretrained.layer3.18.bn3.bias", "pretrained.layer3.18.bn3.running_mean", "pretrained.layer3.18.bn3.running_var", "pretrained.layer3.19.conv1.weight", "pretrained.layer3.19.bn1.weight", "pretrained.layer3.19.bn1.bias", "pretrained.layer3.19.bn1.running_mean", "pretrained.layer3.19.bn1.running_var", "pretrained.layer3.19.conv2.weight", "pretrained.layer3.19.bn2.weight", "pretrained.layer3.19.bn2.bias", "pretrained.layer3.19.bn2.running_mean", "pretrained.layer3.19.bn2.running_var", "pretrained.layer3.19.conv3.weight", "pretrained.layer3.19.bn3.weight", "pretrained.layer3.19.bn3.bias", "pretrained.layer3.19.bn3.running_mean", "pretrained.layer3.19.bn3.running_var", "pretrained.layer3.20.conv1.weight", "pretrained.layer3.20.bn1.weight", "pretrained.layer3.20.bn1.bias", "pretrained.layer3.20.bn1.running_mean", "pretrained.layer3.20.bn1.running_var", "pretrained.layer3.20.conv2.weight", "pretrained.layer3.20.bn2.weight", "pretrained.layer3.20.bn2.bias", "pretrained.layer3.20.bn2.running_mean", "pretrained.layer3.20.bn2.running_var", "pretrained.layer3.20.conv3.weight", "pretrained.layer3.20.bn3.weight", "pretrained.layer3.20.bn3.bias", "pretrained.layer3.20.bn3.running_mean", "pretrained.layer3.20.bn3.running_var", "pretrained.layer3.21.conv1.weight", "pretrained.layer3.21.bn1.weight", "pretrained.layer3.21.bn1.bias", "pretrained.layer3.21.bn1.running_mean", "pretrained.layer3.21.bn1.running_var", "pretrained.layer3.21.conv2.weight", "pretrained.layer3.21.bn2.weight", "pretrained.layer3.21.bn2.bias", "pretrained.layer3.21.bn2.running_mean", "pretrained.layer3.21.bn2.running_var", "pretrained.layer3.21.conv3.weight", "pretrained.layer3.21.bn3.weight", "pretrained.layer3.21.bn3.bias", "pretrained.layer3.21.bn3.running_mean", "pretrained.layer3.21.bn3.running_var", "pretrained.layer3.22.conv1.weight", "pretrained.layer3.22.bn1.weight", "pretrained.layer3.22.bn1.bias", "pretrained.layer3.22.bn1.running_mean", "pretrained.layer3.22.bn1.running_var", "pretrained.layer3.22.conv2.weight", "pretrained.layer3.22.bn2.weight", "pretrained.layer3.22.bn2.bias", "pretrained.layer3.22.bn2.running_mean", "pretrained.layer3.22.bn2.running_var", "pretrained.layer3.22.conv3.weight", "pretrained.layer3.22.bn3.weight", "pretrained.layer3.22.bn3.bias", "pretrained.layer3.22.bn3.running_mean", "pretrained.layer3.22.bn3.running_var".

**Comment by wuhuikai** [comment]
```
CUDA_VISIBLE_DEVICES=4,5,6,7 python test.py --dataset ade20k --model encnet --jpu --aux --se-loss --backbone resnet50 --resume 'runs/ade20k/encnet/encnet_res50_ade20k_train/model_best.pth.tar' --split test --mode test
```

**Comment by Onimee58** [comment]
thanx a lot 👍
