### ISSUE TITLE
DeepLabV3+JPU  pre-model download error

### ISSUE THREAD

**Issue by onefish51** [wuhuikai/FastFCN#41]
谷歌云端硬盘上的pre-model 
![image](https://user-images.githubusercontent.com/21029719/64237629-4df7aa80-cf2f-11e9-9bec-9982d4a7594a.png)
是488M，但是我下载下来却是511.9MB
![image](https://user-images.githubusercontent.com/21029719/64237733-86978400-cf2f-11e9-88d3-fbf3fe891d86.png)
然后我用The Unarchiver解压缩“deeplab_jpu_res50_pcontext.pth.tar”，出现报错，提示数据损坏
![image](https://user-images.githubusercontent.com/21029719/64237895-e3933a00-cf2f-11e9-8ecb-33fc1601f5da.png)
我用mac自带的解压缩工具解压后却生成一个新的文件名为“deeplab_jpu_res50_pcontext.pth.tar.cpgz”的压缩文件，再次解压缩这个文件却重新生成了一个“deeplab_jpu_res50_pcontext.pth.tar”，这样不断循坏。
你好，可以重新提供一个百度云的地址？谢谢

**Comment by wuhuikai** [comment]
`.pth.tar`文件不用解压，直接使用即可。你可以先尝试用下载到的模型运行一下测试代码~

**Comment by onefish51** [comment]
OK，thanks
