### ISSUE TITLE
Is i have to compile pytorch from source?

### ISSUE THREAD

**Issue by Anikily** [wuhuikai/FastFCN#44]
python scripts/prepare_pcontext.py
/home/yulu/anaconda3/envs/fastfcn/lib/python3.5/site-packages/torch/utils/cpp_extension.py:166: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Downloading /home/yulu/.encoding/data/downloads/VOCtrainval_03-May-2010.tar from http://host.robots.ox.ac.uk/pascal/VOC/voc2010/VOCtrainval_03-May-2010.tar...
 16%|█████████████████████▊                                                                                                               | 215923/1313517 [02:09<04:19, 4228.91KB/s]

Is this warning maters?
my pytorch version:1.1.0
python:3.5

**Comment by wuhuikai** [comment]
Just ignore it : )
