### ISSUE TITLE
Pacal_context:Is mask in train.pth and val.pth identical to original mask?

### ISSUE THREAD

**Issue by Anikily** [wuhuikai/FastFCN#46]
I mean the class order in mask, in code,
mapping = np.sort(np.array([
            0, 2, 259, 260, 415, 324, 9, 258, 144, 18, 19, 22, 
            23, 397, 25, 284, 158, 159, 416, 33, 162, 420, 454, 295, 296, 
            427, 44, 45, 46, 308, 59, 440, 445, 31, 232, 65, 354, 424, 
            68, 326, 72, 458, 34, 207, 80, 355, 85, 347, 220, 349, 360, 
            98, 187, 104, 105, 366, 189, 368, 113, 115]))
But i fond the mapping in train.pth is :
mapping = [0,   2,   9,  18,  19,  22,  23,  25,  31,  33,  34,  44,  45,
        46,  59,  65,  68,  72,  80,  85,  98, 104, 105, 113, 115, 144,
       158, 159, 162, 187, 189, 207, 220, 232, 258, 259, 260, 284, 295,
       296, 308, 324, 326, 347, 349, 354, 355, 360, 366, 368, 397, 415,
       416, 420, 424, 427, 440, 445, 454, 458]

**Comment by wuhuikai** [comment]
They're identical except the order. Does the order cause any problem?

**Comment by Anikily** [comment]
I just w
