### ISSUE TITLE
performance problem when training ADE20k

### ISSUE THREAD

**Issue by Anikily** [wuhuikai/FastFCN#50]
When i train ADE20k and cropsize=520,i have got a worse performance than original crop-size 480,do you have any idea why this happen?是学习率要调高吗？

**Comment by wuhuikai** [comment]
This is caused by the different distribution between the training image and testing image. With larger crop size in the training phase, the size in the testing phase should also be enlarged.

**Comment by Anikily** [comment]
@wuhuikai checkpoint have record the crop size of training phase,which are equal to the crop-size of testing phase.

**Comment by wuhuikai** [comment]
In testing phase, `ms` and `flip` are employed. The scales in `ms` should be manually tuned.

**Comment by Anikily** [comment]
So, if i want to train ADE20k on crop-size=520 for better performance, how should i modify the code?

**Comment by wuhuikai** [comment]
Tuning this [line](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/test.py#L61) on the `val` set by yourself.

**Comment by HolmesShuan** [comment]
@Anikily @wuhuikai 
Hi, I wonder why the multiscale testing setting in [FastFCN](https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/experiments/segmentation/test.py#L61) is different from [PyTorch-Encoding](https://github.com/zhanghang1989/PyTorch-Encoding/blob/ae218bf96115b613732a2be40b0fbd3ee15b7a7c/experiments/segmentation/test.py#L69).

FastFCN:
```python
scales = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25] if args.dataset == 'citys' else \
        [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
```
Enocding:
```python
scales = [0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25] if args.dataset == 'citys' else \
        [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
```
Thanks.

**Comment by Anikily** [comment]
@HolmesShuan In my experiment, more scales get bad results

**Comment by HolmesShuan** [comment]
Thanks~

**Comment by wuhuikai** [comment]
The scales in `FastFCN` is consistent with `PyTorch-Encoding` under this [commit](https://github.com/zhanghang1989/PyTorch-Encoding/blob/c2cb2aab69d5d276fbcb847fb8277c1a52947661/experiments/segmentation/test.py#L63).

**Comment by HolmesShuan** [comment]
@Anikily @wuhuikai Thanks for the quick responses.
