### ISSUE TITLE
Error checking compiler version for cl: [WinError 2]请问这个问题怎么解决

### ISSUE THREAD

**Issue by xiaokeaiyayaya** [wuhuikai/FastFCN#51]

**Comment by xiaokeaiyayaya** [comment]
warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by wuhuikai** [comment]
Please provide the configurations of your system.

**Comment by xiaokeaiyayaya** [comment]
win10;
cuda9.2;
pytorch1.3.0

**Comment by wuhuikai** [comment]
Please use Linux systems such as Ubuntu 16.04.

**Comment by xiaokeaiyayaya** [comment]
好吧

**Comment by wuhuikai** [comment]
@xiaokeaiyayaya The code in branch `latest` is now ready, which uses official `SyncBatchNorm` and can run on all OS with `PyTorch>=1.1.0`.
