### ISSUE TITLE
Comparison with deeplab v3

### ISSUE THREAD

**Issue by siju-samuel** [wuhuikai/FastFCN#53]
**deeplabv3 resnet50**
[Model size: 98MB](https://download.pytorch.org/models/resnet50-19c8e357.pth)
Parameters: 39,638,869

**deeplabv3 resnet50 with JPU**
[Model size: 489MB](https://drive.google.com/open?id=11s20bUkPrZXXmFqYpwC_h1G57CB8g2u9)
Parameters: 63,931,934

https://github.com/wuhuikai/FastFCN/blob/097e7130f77a15eeca12f37a0afcf2f8f7f90439/encoding/models/deeplabv3.py#L16

If you see the above link, we can see the architecture with JPU contains **[resnet50(dialations removed) + JPU + ASPP_Module + FCNHead]** whereas normal deeplabv3 consists of **[resnet50 + ASPP_Module]** 
This difference explains the memory/parameter size

Please correct me if im wrong. Im not able to understand how this will improve the memory footprint & speed of the network in comparison with deeplabv3 with/without jpu.

**Comment by wuhuikai** [comment]
1. The model size of DeepLab-V3 is `338MB`**[resnet50+ASPP_Module+FCNHead]**.
2. `FCNHead` is used for deep supervision.
3. The output stride of `DeepLab-V3` is `8` while that of `DeepLab-V3-JPU` is `32`, thus `DeepLab-V3-JPU` can improve memory footprint and speed.
