### ISSUE TITLE
Regarding  the computation time and memory footprint of JPU based models

### ISSUE THREAD

**Issue by amitsrivastava78** [wuhuikai/FastFCN#55]
Hi @wuhuikai ,
              First of all i would like to congratulate you on the excellent paper you have written, I have gone though your paper and source code and i have few queries about this : -

1. As per the paper and the results you have published in the github, these seems to be improvement in terms of mIOU and FPS compared to the model which does not have the JPU, Can you please explain in detail how this is happening ? As i can see and which is evident from your JPU diagram as well that you add JPU unit in the existing model. This make the number of parameters more and hence increasing the memory and computation cost . So i want to know how exactly the FPS is going up.

2. In  the paper page 2 listing the advantages of JPU you have mentioned following : -

> the computation time and memory footprint of the whole segmentation framework can be reduced by a factor of more than 3 and meanwhile achieves better performance

Since you are adding more extra JPU unit which contains dialated convolutions as well, the parameters will go up, so how we can realise the above statement from you(Memory foot print). 

_

Regards
Amit

**Comment by wuhuikai** [comment]
The output stride of models w/o JPU is 8, while the output stride of models w/ JPU is 32.

**Comment by amitsrivastava78** [comment]
@wuhuikai , can you please explain your comments in details 

> The output stride of models w/o JPU is 8, while the output stride of models w/ JPU is 32.

How this will reduce the model size if the JPU is add on on top of existing mode ?

Regards
Amit

**Comment by wuhuikai** [comment]
Please see Figure 1 and Figure 2. Our method can not reduce the model size but reduce the running time and GPU memory usage.

**Comment by amitsrivastava78** [comment]
![image](https://user-images.githubusercontent.com/30853054/68288700-e84ca980-00aa-11ea-8c51-2f8c605f32e1.png)

The above data that we gathered does not display the same results claimed by the paper.

Regards
Amit

**Comment by wuhuikai** [comment]
In the above table, GPU Memory is measured in the inference phase; but the GPU memory mentioned in the paper refers to the training phase.
