### ISSUE TITLE
Some problem when running test.py and train.py

### ISSUE THREAD

**Issue by pp00704831** [wuhuikai/FastFCN#58]
Hi, I am a beginner in deep learning.
Some problem occurred when I was running the code.
First, I use the command 「 tar -xvf encnet_jpu_res50_pcontext.pth.tar 」 to extract the tar file, but it fails.
Second, if i successfully extract the file and get checkpoint, which file should I put my checkpoint in ? Where should I extract my checkpoint file to? 
Thank You!

**Comment by wuhuikai** [comment]
It's not a `tar` file. Directly put the file into a folder and use it with `--resume`.

**Comment by pp00704831** [comment]
Thanks you, so where should I put my file ? You means that when I successfully put my file, 
and use --resume encnet_jpu_res50_pcontext.pth.tar then I can run the test.py ?
我也會說中文，我們也可以用中文對談， 謝謝你。

**Comment by pp00704831** [comment]
Because I did not see this problem pages before, so maybe I should find the answers here, thank you for your quickly reply.

**Comment by wuhuikai** [comment]
You're right, using `--resume` to run `test.py`.

**Comment by pp00704831** [comment]
Hello, I met this problem:
/home/tsai/anaconda3/envs/python3.5/lib/python3.5/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Segmentation fault (core dumped)

I used the environment python=3.5 , pytorch1.0 , cuda=9.0 
Do I need to change nn.functional.upsample into nn.functional.interpolate ? I think that I should not change the original better. 
Thank you

**Comment by wuhuikai** [comment]
What's your OS? The code is only tested on Ubuntu 16.04 LTS.

**Comment by pp00704831** [comment]
I used Ubuntu 18.04, so It can't run train.py and test.py on the Ubuntu 18.04 system?

**Comment by wuhuikai** [comment]
I'm not sure about this.

**Comment by pp00704831** [comment]
Okay, I will first change the python 3.5 to python 3.6 first, sorry for bothering you so many times.

**Comment by pp00704831** [comment]
Hello, I have changed my OS on Ubuntu 16.04, python=3.5, pytorch=1.0, cuda=9.0.
I used this to run codes:  
python test.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --resume encnet_jpu_res50_pcontext.pth.tar --split val --mode testval
But an error happened:
ValueError: batch_size should be a positive integeral value, but got batch_size=0

I found that if i did not set any batch_size, it will be batch_size = 16 automatically , but the error still happened.
Thank you !

**Comment by wuhuikai** [comment]
Is the dataset well-prepared?

**Comment by pp00704831** [comment]
Well... after I reinstalled the datasets  , it could work smoothly. Thank you very much.

**Comment by pp00704831** [comment]
Hello, I want to retrain on the model, but I want to use the checkpoint you have gave for testing 
' encnet_jpu_res50_pcontext.pth.tar ' 
So could I use the command like that for more training based on these parameters?
python train.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --checkname encnet_res50_pcontext  ----resume encnet_jpu_res50_pcontext.pth.tar

Because I want to do some simple experiment I don't want to train too many epochs 
Thanks you!

**Comment by wuhuikai** [comment]
Please use `--ft` and use `> 1` GPU.

**Comment by pp00704831** [comment]
Thanks you very much! I will try that.

**Comment by pp00704831** [comment]
Sorry to bother you again. 
Because I want to do some experiment on the loss function, I added other loss function on it , but when I import the function code, it seems that it can not directly import other function.
I added the code in customize.py .
![Selection_003](https://user-images.githubusercontent.com/57279608/71513336-cfa38780-28d4-11ea-9e33-58d87eecb6cb.png)
My question is that whether we need to do some changes on setup.py ?
Because I think the error might come from that. 
Sorry to bother you so many times, I very appreciate your assistance.

**Comment by pp00704831** [comment]
I have successfully modified it, but I still feel strange why we can not import the code from other ?
I modified it by writing them in the same code rather than call(import) from other code.
Thanks you very much!

**Comment by wuhuikai** [comment]
There're 2 ways:
1. If you install by `python setup.py install`, you need to uninstall and reinstall it after modification.
2. Installing by `python setup.py develop`

**Comment by pp00704831** [comment]
I got it! Thanks you.
