### ISSUE TITLE
ImageNet pre-trained model

### ISSUE THREAD

**Issue by SeokjuLee** [wuhuikai/FastFCN#60]
Hi, thanks for your work.
Did you initialize your backbone architecture (ResNet50 or 101) with the ImageNet pre-trained model?
Have you tried some ablation experiments, such as training with or without the ImageNet pre-trained model?

**Comment by wuhuikai** [comment]
All the results are initialized with models pre-trained on ImageNet; We do not have any experiments w/o ImageNet pretraining since it will lead to poor performance as other papers state.
