### ISSUE TITLE
Problem about  dilated convolutions

### ISSUE THREAD

**Issue by FlyingGaifield** [wuhuikai/FastFCN#62]
Good job! But I still have some confusion about the claim that dilated convolutions bring heavy computation complexity and memory footprint.

Can you explain the reason and more about it?
THX

**Comment by wuhuikai** [comment]
It's not dilated convolution but the dilated backbone.
The dilated backbone removes the last two downsampling operations from e.g. ResNet, thus, bring heavy computation complexity and memory footprint.
