### ISSUE TITLE
Questions about the SE-loss and  Aux-loss

### ISSUE THREAD

**Issue by meanmee** [wuhuikai/FastFCN#64]
Hi, first thank you for the great work.
I just checked the codes and also had run some scripts. I am confused with the final loss which is composited with three individual losses. could you tell what is the se-loss and the aux-loss used for.

**Comment by wuhuikai** [comment]
Please refer to `Context Encoding for Semantic Segmentation`. In a word, se-loss is sth like classification loss and aux-loss is deep supervision.

**Comment by meanmee** [comment]
Is se-loss good at solving data-unbalanced problems? cuz my experiments based on my own dataset showed this benefit. 
actually I don't know if if is because of se-loss. the results are just getting better trained on your codes

**Comment by wuhuikai** [comment]
I think that `se-loss` can solve aera-unbalanced problems in a degree.

**Comment by meanmee** [comment]
![image](https://user-images.githubusercontent.com/8026086/78977664-18f9a900-7b4b-11ea-8eb8-b005839b2f2a.png)
Why the results are like this. the while lane should be in a solid way instead of the dot form. 
Is it because of the dilation convolution?

**Comment by wuhuikai** [comment]
I'm not sure. Maybe you can try `dice` loss.

**Comment by meanmee** [comment]
But it works fine when training it with BiSeNet with just one single ce-loss.

**Comment by wuhuikai** [comment]
Maybe you can add a 3x3 conv at the end of JPU.
