### ISSUE TITLE
how to use test_single_image.py

### ISSUE THREAD

**Issue by TheRunningHorse** [wuhuikai/FastFCN#66]
I use test_single_image_image.py by
python -m experiments.segmentation.test_single_image --input-path path_to_image --save-path save_path --model-zoo encnet_resnet50_ade 
and i fail
![1](https://user-images.githubusercontent.com/62589403/79961029-b55f6c00-84b8-11ea-9eab-85d861b9bd05.png)

**Comment by TheRunningHorse** [comment]
I added jpu ='JPU' in line 30 of test_single_image.py
but a new error was raised
![799631043](https://user-images.githubusercontent.com/62589403/79965424-919f2480-84be-11ea-8bb1-a2e367170103.jpg)

**Comment by wuhuikai** [comment]
`--model-zoo` is not supported.

**Comment by TheRunningHorse** [comment]
so how do I test on single image？

**Comment by wuhuikai** [comment]
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m experiments.segmentation.test_single_image --dataset [pcontext|ade20k] \
    --model [encnet|deeplab|psp] --jpu [JPU|JPU_X] \
    --backbone [resnet50|resnet101] [--ms] --resume {MODEL} --input-path {INPUT} --save-path {OUTPUT}
```

**Comment by TheRunningHorse** [comment]
Thanks a lot
