### ISSUE TITLE
摄像头视频进行实时显示？

### ISSUE THREAD

**Issue by Iseady** [wuhuikai/FastFCN#67]
首先非常感谢您的代码。我是个新手，很抱歉打扰您。
1.更改新代码后，单GPU训练预测更改代码方法一样吗？
2.您可以做一个可以摄像头视频进行实时显示的吗？
3.您可以把您的训练结果和大家共享一下吗？
4.您可以做一个比较完整包括训练测试的文档吗？
再次感谢您，希望您能帮助我

**Comment by wuhuikai** [comment]
1. 单GPU训练建议使用latest分支；master分支的话修改方式与之前相同
2. 请参见`test_single_image.py`自行修改
3. 模型已经分享，详见[link](https://github.com/wuhuikai/FastFCN#train-and-test)
4. 详见ReadMe
