### ISSUE TITLE
ModuleNotFoundError: No module named 'detail'

### ISSUE THREAD

**Issue by hiepph** [wuhuikai/FastFCN#7]
Hi, I was trying to run the test script

```
CUDA_VISIBLE_DEVICES=0,1,2,3 python test.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
--backbone resnet50 --resume {MODEL} --split val --mode test
```

Then this error popped up:

```
  File "[...]/FastFCN/encoding/datasets/pcontext.py", line 25, in __init__
    from detail import Detail
ModuleNotFoundError: No module named 'detail
```

Are we missing a `detail.py` module here?

**Comment by wuhuikai** [comment]
`python scripts/prepare_pcontext.py` will install the `Detail` package automatically.

**Comment by abhimanyuchadha96** [comment]
It gives an error that the Numpy API has been deprecated and thus I am unable to install it.

**Comment by wuhuikai** [comment]
Please give the error message in detail.
