### ISSUE TITLE
parameters of that JPU module

### ISSUE THREAD

**Issue by xuanxiaoliqu** [wuhuikai/FastFCN#72]
Hello, I want to know why the parameters of that JPU module are not passed into the optimizer in the late training period.How did you set it up，thank you

**Comment by wuhuikai** [comment]
The params are added [here](https://github.com/wuhuikai/FastFCN/blob/126661b0eb6053ce35b3c778a7d402f0338d98b7/experiments/segmentation/train.py#L60).
