### ISSUE TITLE
Performance about JPU_X

### ISSUE THREAD

**Issue by tjj1998** [wuhuikai/FastFCN#73]
Thanks for your excellent work! I tried encnet-JPU_X which obtained 55.12% with 59 classes on pcontext with ms. It's a big  promote. In my opinion, JPU_X solve the problem of fusing feature maps from different layers. JPU fuses 3 layers together, and JPU_X fuses 64-32 first, and then 64-16. So, I have a assumption, have you tried 32-16 first, and then 64-32? Is this method performs worser?I know maybe the origin method more similar to the dilated convolution, just a simple guess.

Another question, are you preparing to add the backbone? such as xception and resnest, from PyTorch-Encoding?  

Thanks for your work again.

**Comment by wuhuikai** [comment]
1. I didn't try `32-16 first, and then 64-32`, it may achieve a better performance.
2. I prepare to `add xception and resnest`, but currently I do not have time to do this.

Pull requests are welcome for both questions.
