### ISSUE TITLE
Hello, What CUDA extentsion operations have been replaced by pure python?

### ISSUE THREAD

**Issue by shoutOutYangJie** [wuhuikai/FastFCN#75]
One yeas ago, I have read your code. Recently, I notice that you update you code, and can run your FastFCN on any OS. So I want to ask you what CUDA custom operation you have replaced?
Because I want to learn how to do it. Thank you!

**Comment by wuhuikai** [comment]
Basically, I rewrite the `sync_bn` with python, see [here](https://github.com/wuhuikai/FastFCN/blob/master/encoding/functions/syncbn.py).
