### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ResNet: size mismatch

### ISSUE THREAD

**Issue by DancingJane** [wuhuikai/FastFCN#76]
Thank you for your work.
I meet a problem. When I train the net according to the wiki, the error "RuntimeError: Error(s) in loading state_dict for ResNet" appears. I use the weight file from  https://hangzh.s3.amazonaws.com/encoding/gluoncvth/resnet50-0ef8ed2d.zip. the error description in detail is as follows. 

Namespace(aux=True, aux_weight=0.2, backbone='resnet50', base_size=520, batch_size=16, checkname='encnet_res50_ade20k_train', crop_size=480, cuda=True, dataset='ade20k', dilated=False, epochs=120, ft=False, jpu='JPU', lateral=False, lr=0.01, lr_scheduler='poly', mode='testval', model='encnet', model_zoo=None, momentum=0.9, ms=False, no_cuda=False, no_val=False, resume=None, save_folder='experiments/segmentation/results', se_loss=True, se_weight=0.2, seed=1, split='val', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
BaseDataset: base_size 520, crop_size 480
len(img_paths): 20210
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Files/segmentation/FastFCN/experiments/segmentation/train.py", line 176, in <module>
    trainer = Trainer(args)
  File "/Files/segmentation/FastFCN/experiments/segmentation/train.py", line 55, in __init__
    base_size = args.base_size, crop_size = args.crop_size)
  File "/Files/segmentation/FastFCN/encoding/models/__init__.py", line 18, in get_segmentation_model
    return models[name.lower()](**kwargs)
  File "/Files/segmentation/FastFCN/encoding/models/encnet.py", line 146, in get_encnet
    model = EncNet(datasets[dataset.lower()].NUM_CLASS, backbone=backbone, root=root, **kwargs)
  File "/Files/segmentation/FastFCN/encoding/models/encnet.py", line 24, in __init__
    norm_layer=norm_layer, **kwargs)
  File "/Files/segmentation/FastFCN/encoding/models/base.py", line 39, in __init__
    norm_layer=norm_layer, root=root)
  File "/Files/segmentation/FastFCN/encoding/dilated/resnet.py", line 263, in resnet50
    get_model_file('resnet50', root=root)), strict=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 843, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for bn1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for bn1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for bn1.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for bn1.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
	size mismatch for layer1.0.downsample.0.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).

**Comment by wuhuikai** [comment]
You can modify the model according to `gluoncvth` for now.
I'm considering uploading the old `.pth` file or update the code to `gluoncvth` within a month. Stay tune ...
