### ISSUE TITLE
model parameter

### ISSUE THREAD

**Issue by LiouCZ** [wuhuikai/FastFCN#78]
The last three layers of the pre training resnet model don't seem to be used, but they will be saved when the model is saved

**Comment by wuhuikai** [comment]
You can remove this [line](https://github.com/wuhuikai/FastFCN/blob/126661b0eb6053ce35b3c778a7d402f0338d98b7/encoding/dilated/resnet.py#L175) and set `strict=False` when load the pretrained model.
