### ISSUE TITLE
预训练模型无法下载

### ISSUE THREAD

**Issue by AishuaiYao** [wuhuikai/FastFCN#79]
https://hangzh.s3.amazonaws.com/encoding/models/resnet50-ebb6acbb.zip 无法下载@wuhuikuai，您好，这个模型无法下载，没法实验您的单张预测功能，请问这是不是你的私人仓库啊，我该怎么运行您的代码呢，谢谢

**Comment by wuhuikai** [comment]
如果只是测试的话，不用下载上述模型；而是下载[此处](https://github.com/wuhuikai/FastFCN#pcontext) 对应的`GoogleDrive`中的模型。
