### ISSUE TITLE
when run test_single_image, Model file /root/.encoding/models/resnet50-ebb6acbb.pth is not found

### ISSUE THREAD

**Issue by tomjerrygithub** [wuhuikai/FastFCN#80]
how to fix this ?

`python -m experiments.segmentation.test_single_image --dataset  pcontext --model  encnet --jpu JPU     --ms  --resume  encnet_jpu_res50_pcontext.pth.tar  --input-path  ../semantic-segmentation-pytorch/segment_test.jpg  --save-path  segment_test.png`

**Comment by wuhuikai** [comment]
Set `pretrained=False` [here](https://github.com/wuhuikai/FastFCN/blob/126661b0eb6053ce35b3c778a7d402f0338d98b7/encoding/models/base.py#L38).
