### ISSUE TITLE
Dilated convolution in JPU

### ISSUE THREAD

**Issue by frk1993** [wuhuikai/FastFCN#82]
Hi Guys,  
I read the paper and I have a question. 
In the paper it is outlinrd that dilated convs are very expensive and therefore the novel JPU is introduced. However, in the JPU you use dilated convs with rates 2, 4, 8. 
Then the JPU is also very expensive. Am I right ?

Thanks!

**Comment by wuhuikai** [comment]
The dilated backbone is expensive, the dilated conv is not expensive at all.

**Comment by frk1993** [comment]
Thank you, I get your point. But I am understanding the approach right, you use dilated convs in the JPU?

**Comment by wuhuikai** [comment]
Yes
