### ISSUE TITLE
Backbone weights download links not working anymore

### ISSUE THREAD

**Issue by Khroto** [wuhuikai/FastFCN#86]
Download links for the backbone do not seem to work anymore.

I've tested with Resnet50 (https://hangzh.s3.amazonaws.com/encoding/models/resnet50-ebb6acbb.zip) and Resnet 101 (https://hangzh.s3.amazonaws.com/encoding/models/resnet101-2a57e44d.zip) too.

I also tried to use torchivision weights instead, but I got matching errors when trying to load them.

Could you consider reuploading the weights? 
That would be very helpful!

**Comment by wuhuikai** [comment]
Sure, I'll upload all the weights in this Sunday : )

**Comment by Khroto** [comment]
Thank you!
Looking forward to it then :)

**Comment by wuhuikai** [comment]
Here is the [link](https://drive.google.com/drive/folders/1YFv8JR5IYol2_kDHPMXfUkjXt4Z6t_rh?usp=sharing) : ) @Khroto

**Comment by Khroto** [comment]
Hi @wuhuikai, sorry to post after you closed the thread but it seems that an access right is needed to access the above link. Would it be possible to make it publicly accessible or otherwise give me the access right? Thanks!

And thank you anyway for having re-uploaded the weights.

**Comment by wuhuikai** [comment]
Could you please try it again? I have already set it public to everyone.

**Comment by Khroto** [comment]
I could indeed download it successfully this time, thank you.
