### ISSUE TITLE
downloading model file erro

### ISSUE THREAD

**Issue by Ritian-Li** [wuhuikai/FastFCN#89]
Model file /root/.encoding/models/resnet50-ebb6acbb.pth is not found. Downloading.
Downloading /root/.encoding/models/resnet50-ebb6acbb.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet50-ebb6acbb.zip...
 
and this website...
![image](https://user-images.githubusercontent.com/60093100/94504053-7806c380-023a-11eb-8e21-bfc081613a74.png)

**Comment by wuhuikai** [comment]
See [Here](https://github.com/wuhuikai/FastFCN/issues/86#issuecomment-683407808).
