### ISSUE TITLE
can't download the pretrained model

### ISSUE THREAD

**Issue by ren-meijian** [wuhuikai/FastFCN#90]
Hello, according to the Google Drive link you provided, I have tried to download it with A VPN for many times, but all of them failed automatically due to the slow speed. Could you please send resnet50-ebb6acbb.pth to my email address？
2321968768@qq.com
Thank you very much!

**Comment by AleBasso80** [comment]
Hello,
I'm not able too....

**Comment by s-bei** [comment]
Hello,
I had the same problem and was unable to download the pre-training model of Resnet-50!Could you please send it to my e-mail address?
an_shipeng@tju.edu.cn
Thank you very much！
