### ISSUE TITLE
the method when train with PSP head

### ISSUE THREAD

**Issue by wo712268** [wuhuikai/FastFCN#91]
Hello! I read your paper and try to reproduction the code. Now i wrote the JPU with the psp head, but i have a problem,when train with psp head , we train the baseline fast, then fine tuning the model.
Did i need to train the baseline and JPU and PSP seperated? Or train the baseline+JPU, then PSP?
Thank you for your response!

**Comment by wuhuikai** [comment]
I prefer to train baseline + JPU + PSP jointly. If baseline refers to a backbone for classification, then I suggest that train baseline first and then JPU + PSP jointly.
