### ISSUE TITLE
Is the training speed of pure pytorch version faster than pure python version?

### ISSUE THREAD

**Issue by Anikily** [wuhuikai/FastFCN#92]

**Comment by wuhuikai** [comment]
First, there's no pure python version.
Second, pure pytorch version is slightly faster than 3rd-party SyncBN version.

**Comment by Anikily** [comment]
> First, there's no pure python version.
> Second, pure pytorch version is slightly faster than 3rd-party SyncBN version.

i mean, is latest version faster than master?

**Comment by wuhuikai** [comment]
No big difference.
