### ISSUE TITLE
Access denied when trying to download models.

### ISSUE THREAD

**Issue by CN-HaoJiang** [wuhuikai/FastFCN#93]
Hello!
I have tried to run experiments.segmentation.test and experiments.segmentation.test_single_image. However, I encounted a problem that downloading failed.
![G`K5D1}K$U JU86XUM@}HKQ](https://user-images.githubusercontent.com/48546669/111722662-41327180-889d-11eb-9d78-eb1bf52e60d7.png)

![{V$R94HYVG JQ{9(}MP9DJJ](https://user-images.githubusercontent.com/48546669/111722598-206a1c00-889d-11eb-9c3e-30ed1b4be87a.png)

![X2(Z~(S ~IB% P~26K}1I9H](https://user-images.githubusercontent.com/48546669/111722493-ec8ef680-889c-11eb-9d17-f63c8f113dd6.png)

**Comment by wuhuikai** [comment]
Please refer to #86

**Comment by CN-HaoJiang** [comment]
Thank you for replying, The link is accessible now :}
