### ISSUE TITLE
训练时出现 raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".

### ISSUE THREAD

**Issue by XGQ1n** [wuhuikai/FastFCN#95]
在训练CUDA_VISIBLE_DEVICES=0,1,2,3 python -m experiments.segmentation.train --dataset pcontext --model encnet --jpu JPU --aux --se-loss --backbone resnet50 --checkname encnet_res50_pcontext 时 
报错：raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: C:\Users\NEFU-HJP/.encoding/data\VOCdevkit/VOC2010\train.pth is a zip archive (did you mean to use torch.jit.load()?)

**Comment by wuhuikai** [comment]
windows环境吗？

**Comment by XGQ1n** [comment]
> Windows环境吗？

是的

**Comment by wuhuikai** [comment]
有更详细的报错信息吗？

**Comment by XGQ1n** [comment]
> 有更详细的报错信息吗？

**Comment by XGQ1n** [comment]
> 有更详细的报错信息吗？

![79634b1bb3360b6432115ae09cb7772](https://user-images.githubusercontent.com/72644583/112927957-6601d100-9148-11eb-9bba-bac1cf719adf.png)

**Comment by wuhuikai** [comment]
只有这些信息我也不知道错误在哪
