### ISSUE TITLE
不能下载

### ISSUE THREAD

**Issue by LinuxAIoT** [wuhuikai/FastFCN#96]
作者你好，我在进行测试无法下载https://hangzh.s3.amazonaws.com/encoding/models/resnet101-2a57e44d.zip这个文件，请问如何找到并下载这些所需要的文件。

**Comment by wuhuikai** [comment]
Please refer to #86

**Comment by MyHubTo** [comment]
thank u

**Comment by LinuxAIoT** [comment]
thank u
