### ISSUE TITLE
How could I set "resume" while running test_single_image?

### ISSUE THREAD

**Issue by CN-HaoJiang** [wuhuikai/FastFCN#99]
Hello!

When I run test_single_image.py, I tried to set resume as path of resnet101-2a57e44d.pth and encountered an error. 

> File "G:/gitfolder/FastFCN/experiments/segmentation/test_single_image.py", line 43, in test
    model.load_state_dict(checkpoint['state_dict'], strict=False)
KeyError: 'state_dict

I doubted that there existed a problem with "resume".
Waiting for your reply.

Thank you!

**Comment by wuhuikai** [comment]
It can only load checkpoints saved by the training script.

**Comment by CN-HaoJiang** [comment]
Hi @wuhuikai, sorry to post after you closed the thread but I met a problem with the pickle module.

This time I set resume as the path of pretrained "encnet_res101_ade20k_train.sh". However, an error occured as...
![}4AAUTCN7T}A8)SLZZ}{3IO](https://user-images.githubusercontent.com/48546669/119925269-b3af8400-bfa7-11eb-8d4c-85d49720b756.png)

Call stack is as follows.
![}IEWVYP$X)ES@6CO431}7JR](https://user-images.githubusercontent.com/48546669/119925365-e22d5f00-bfa7-11eb-87f7-4e1098380215.png)

The inputting parameters are...
![_Q2{PBIROWIQG 9P %@8W~P](https://user-images.githubusercontent.com/48546669/119925647-6da6f000-bfa8-11eb-9647-fa76e6b50c7a.png)


The confusing point is that this error don't happen when resume is not setted.

Waiting for your reply:). Thank you!

**Comment by wuhuikai** [comment]
Which version of PyTorch are you using?

**Comment by CN-HaoJiang** [comment]
Pytorch version 1.8.1+cu111 :)

**Comment by wuhuikai** [comment]
Try lower version of pytorch, see 1.4.0

**Comment by CN-HaoJiang** [comment]
Hello!
I've tried torch==1.4.0 & torchvision==0.5.0. However, the problem still exists. Is there any mistake with parameters? :)

**Comment by CN-HaoJiang** [comment]
I execute the programme in Windows10. Is the problem related to OS?

**Comment by wuhuikai** [comment]
That's wired. I don't know but I haven’t try this code on Windows.
